[versions]
minecraft = "26.1.2"

# Fabric
fabric-loader = "0.19.3"
fabric-api = "0.155.2+26.1.2"
mod-menu = "18.0.0"

# Testing
player-roles = "1.9.0-pre.1"

# Fixing
panacea = "0.1.5+26.1.x"

# Libraries
fabric-permissions = "0.7.0"

[libraries]
minecraft = { module = "com.mojang.:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mod-menu = { module = "com.terraformersmc:modmenu", version.ref = "mod-menu" }

# Testing
player-roles = { module = "dev.gegy:player-roles", version.ref = "player-roles" }

# Fixing
panacea = { module = "lgbt.greenhouse.panacea:panacea", version.ref = "panacea" }

# Libraries
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }
